server:
  port: 9090
spring:
  profiles:
#    active: dev
    active: test-docker-db
springdoc:
  swagger-ui:
    enabled: true
    url: swagger.yaml
    try-it-out-enabled: false
    syntax-highlight:
      activated: true